name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'deploy') }}
    steps:
      - uses: actions/checkout@v2

      - name: Detect Node version from .nvmrc
        id: node_version
        run: echo "::set-output name=nvmrc::$(cat .nvmrc)"

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.nvmrc }}

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set env
        run: |
          echo "slide-name=$(echo '${{ github.event.head_commit.message }}' | cut -d' ' -f 2)" >> $GITHUB_ENV

      - name: Install dependencies and Puppeteer
        run: |
          npm ci
          sudo apt-get install libgbm-dev
          npm i puppeteer --no-save

      - name: Build Marp slide deck
        run: |
          CHROME_PATH=$(node .puppeteer.js) npm run build -- ./slides/${{ env.slide-name }}.md --base /presentations-marp/${{ env.slide-name }}/
          touch ./dist/.nojekyll
        env:
          # Please update URL if you want to use custom domain
          URL: https://${{ github.event.repository.owner.name }}.github.io/${{ github.event.repository.name }}

          # Recommend to set lang for your deck to get better rendering for Open Graph image
          LANG: en-US

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
